services:
  push-service:
    build:
      context: .
    image: push-service:latest
    container_name: push-service
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./config/push_service.yaml:/config/push_service.yaml:ro
    restart: unless-stopped
    command:
      - -c
      - /config/push_service.yaml
      - webui