services:
  push-service:
    image: "ghcr.io/aesuli/push_service:latest"
    container_name: push-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./config:/config
    restart: unless-stopped
    command:
      - -c
      - /config/push_service.yaml
      - webui