db_url = sqlite:////data/channels.db
encryption_password_file = /data/channel_db_encryption_password
push_service_email = push_service@example.com
log_dir = /data/logs
host = 0.0.0.0
port = 8000
enable_admin = false
show_home = false
enable_channel_creation = false
otp_secret_file = /data/otp_secret
admin_password_file = /data/admin_password
